# age=int(input("what is your age"))
# if age < 18:
#     print("you cannot buy lottery tickets")
# print(" ")
# month=input("what is your birth month?")
# day=input("what is your birth day?")
# year=input("what is your birth year?")
# print(" ")
# user_name=input("what is your name?")
# print("hello" + user_name)
# print(" ")
# if 4>3:
#     print("4 is greater than 3")
# print(" ")
# random_num=int(input("type a random number"))
# if random_num>10:
#     print("your number is greater than 10")
# if random_num<10:
#     print("your number is smaller than 10")
# print(" ")
# word=input("type a random word")
# word_length = len(word)
# print(word)
# print(word_length)
# print(" ")
# course1=int(input("enter your average for course 1"))
# course2=int(input("enter your average for course 2"))
# course3=int(input("enter your average for course 3"))
# course4=int(input("enter your average for course 4"))
# average1=int(input((course1+course2+course3+course4)/4))
# print(" ")
# grdnlength1=int(input("what is the length of garden 1?"))
# grdnwidth1=int(input("what is the width of garden 1?"))
# print(grdnlength1*grdnwidth1)
# print(" ")
# grdnlength2=int(input("what is the length of garden 2?"))
# grdnwidth2=int(input("what is the width of garden 2?"))
# print(grdnlength2*grdnwidth2)
# print(" ")
# if grdnlength1*grdnwidth1==grdnlength2*grdnwidth2:
#     print("the areas of your gardens match up")
# if grdnlength1*grdnwidth1!=grdnlength2*grdnwidth2:
#     print("the areas of your gardens do not match up")
# print(" ")
# Random=input("type in something random (letter, word, number, etc)")
# if Random<11:
#   print("yay")